# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./resource.h \
    ./resource1.h \
    ./stegosaurus.h

#Source files
SOURCES += ./main.cpp \
    ./stegosaurus.cpp

#Forms
FORMS += ./stegosaurus.ui

#Resource file(s)
RESOURCES += ./stegosaurus.qrc
